apiVersion: v1
kind: Service # this creates ClusterIP service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
   app: nginx
   tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: tcp
    port: {{ .Values.service.port }} #this is service port
    targetPort: {{ .Values.service.targetPort }} # this is container port. we can also give name and provide value in pod definition
