kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
    DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api  
        project: expense
    spec:
      containers:
      - name: backend
        image: rajikakani412/backend:{{ .Values.deployment.version}}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits: # limits should be greater than or equal to requests
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service 
metadata:
  namespace: expense
  name: backend
  
spec:
  selector:
   app: backend
   tier: api
   project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # this is service port
    targetPort: 8080 # this is container port.
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: expense
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage:  {{ .Values.hpa.targetcpuutil }} # usually 75 or more in real env